# Generated by Django 2.1.2 on 2018-12-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-create_time']},
        ),
    ]
