# Generated by Django 2.1.2 on 2019-01-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20181230_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
