# Generated by Django 2.1.2 on 2019-01-02 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_topic_read_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='read_num',
        ),
        migrations.AddField(
            model_name='readnum',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='learning.Topic'),
        ),
    ]
