# Generated by Django 2.1.2 on 2019-01-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_auto_20190102_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='topic',
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
