# Generated by Django 2.1.2 on 2019-01-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20190109_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-create_time']},
        ),
    ]
